# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('region_name', models.CharField(max_length=250)),
                ('district_name', models.CharField(max_length=250)),
                ('state_name', models.CharField(max_length=250)),
            ],
        ),
    ]
