# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCreateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to=product.models.upload_image_path)),
                ('active', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField()),
                ('brand_name', models.CharField(max_length=120)),
                ('model_name', models.CharField(blank=True, max_length=120, null=True)),
                ('model_number', models.CharField(blank=True, max_length=120, null=True)),
                ('colour', models.CharField(blank=True, max_length=120, null=True)),
                ('warranty', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_create', to='seller.SellerProfileModel')),
                ('product_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_location', to='locations.Location')),
            ],
        ),
    ]
